[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
merkle_distributor = "9NVfZpQj1K6xDh2mCBc7PNhAvqyBEvnca9EW1onLukcU"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "Localnet"
cluster = "devnet"
wallet = "/Users/xp/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
