[toolchain]

[features]
seeds = false
skip-lint = false

[programs.mainnet]
cosigner_distributor = "3tLUSygUmiFMPhkaNwhQpX35JXeyYhxLbYDreViaXBSP"
[programs.devnet]
cosigner_distributor = "3tLUSygUmiFMPhkaNwhQpX35JXeyYhxLbYDreViaXBSP"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "mainnet"
cluster = "devnet"

wallet = "/Users/xp/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
